name: "CI/CD"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  dev:
    runs-on: ubuntu-latest
    environment:
      name: dev

    steps:
      - name: Run a one-line script
        run: echo Hello, world!

  qa:
    runs-on: ubuntu-latest
    needs: dev
    environment:
      name: qa

    steps:
      - name: Run a one-line script
        run: echo Hello, world!

  prod:
    runs-on: ubuntu-latest
    needs: qa
    environment:
      name: prod

    steps:
      - name: Run a one-line script
        run: echo Hello, world!
